### ISSUE TITLE
Highlighting is frequently too light to distinguish easily (or at all).

### ISSUE THREAD

**Issue by TricksterWolf** [RogerDodger/WriteOff#18]
I use LED 1080p monitors. The Writeoff site has highlighting that is practically invisible. Most of it could stand to be darkened. Maybe this is unique to my monitors, but I don't have this problem anywhere else on the internet (that I can recall).

The biggest issue is the unselected green lines for author guessing. Those are _almost_ completely invisible. Another example that's not as much of a problem, but still a bit of eye strain, would be the yellow vs. blue background in the prelim how-you-voted slate that shows which stories made the cut.

In general, I think most of those near-#FFFFFF's could be pulled back a lot.

**Comment by RogerDodger** [comment]
I've made the unfocused green lines in guess graph a bit brighter.

Will review the ballot colours later.

**Comment by TricksterWolf** [comment]
The new green is good! But, I think you need to desaturate both greens (i.e. add grey to push it a little toward forest green by raising the R and B values together). The reds are fine, because they're not super-saturated, but your green lines are much too saturated, which makes them a little hard to see even after you've turned things up. Ideally it should be equally easy to see the selected red and selected green lines, so it becomes clear that they're both selected.

As a matter of design (I have a lot of experience with this, so I'm not just talking out my ponut) it's usually better to err on the side of contrast than subtlety. The only downside is that too much contrast could end up being garish, but you're nowhere _near_ garish anywhere on the site. 

That said, most of the color choices on writeoff.me are excellent. You have a good sense of style and an eye for clear design.

The only other color choices I'd recommend changing are the following:

This isn't a necessity, but it would look nice if you made the four main-menu-bars more distinct (i.e. a lot higher saturation and maybe some more hue divergence). I mean the Rules, Prompt/Vote, Fic/Gallery/Guess/Vote/Results, and Discussion bars.

The six colors used in the lists (title blue, gold, silver, bronze, dark blue, light blue) need to be darker and more distinct. I don't think using blue for the title and dark/light lines is a good idea because the text is usually blue (hyperlinks). I'd probably go with a green like you use for the writeoff boxes (the box at the top that has the name of the writeoff), except maybe a little darker for the title, and a little lighter for the light/dark lines. And I'd make the light lines much lighter than the dark lines, for contrast. That would have the added benefit of making silver more distinct (it's bluish), but gold silver and bronze should be much darker too. Especially gold and bronze, they're practically white right now.

Obviously these are just suggestions, but I wouldn't pick if I didn't love the site and the wonderful work you have done for us all. Thank you so much!

And have a happy Hearth's Warming Eve!
/)^3^(\

**Comment by TricksterWolf** [comment]
I think it looks perfect as-is. I'd maybe lighten the light blue just a hair so it's easier to distinguish the lines, but that's all.

**Comment by TricksterWolf** [comment]
Actually, I don't think you need to change anything. Everything looks good.

Though... I might lighten the unselected green and red lines a little now. They're more than dark enough to be seen, but also dark enough to be distracting when the lines are selected. (A compromise might be to lighten all the background lines by half whenever you select a circle.)

**Comment by RogerDodger** [comment]
> (A compromise might be to lighten all the background lines by half whenever you select a circle.)

I tried this and didn't really like the effect.

The lightness on unfocused lines was 92% before. 94% is too hard to see, so I set it to 93%.

**Comment by TricksterWolf** [comment]
Looks perfect. /)^3^(\
