### ISSUE TITLE
Create new scoreboard for art competitions

### ISSUE THREAD

**Issue by baxil** [RogerDodger/WriteOff#27]
Currently, the scoring for art entries counts toward the same scoreboard that that round's writing period qualifies for.  This is highly suboptimal for a number of reasons.

1) Art entries for minifics and short stories count for different numbers of points despite taking the same amount of effort.

2) Scoreboards have previously measured skill in a specific area (writing ponyfic/original fic, at a specific wordcount length), and counting points for activities which are not that skill dilutes that.

3) Individuals who are consistently good at art entries should be rewarded with recognition for that skill, rather than having those contributions diluted by ranking them against authors.

Proposed change:
– Create a third Scoreboard class for Art entries.
– Shift all medals and points from the Art portion of multi-round events into the new scoreboard.
– Remove those medals and points from their current location and recalculate scores accordingly.

Art scoreboard scores should decay only when an art round occurs, and should not contribute to the score decay of writing rounds (though typically there's a writing event attached to the art event, and *that* should cause writing-score decay as normal).

**Comment by RogerDodger** [comment]
Done.
