### ISSUE TITLE
Seperate General Discussion Thread from Story-Specific Comments

### ISSUE THREAD

**Issue by Otterverse** [RogerDodger/WriteOff#28]
In the general contest discussion thread, comments on all stories on included, intermixed with more general comments/discussions directed toward the contest as a whole. It would be nice to have a discussion thread for the contest itself that doesn't include comments on individual stories. Story comments are usually specific to the story itself, and are often made without any knowledge of more general conversations taking place in the main thread. Having such comments injected into that main thread is distracting and confusing to anyone that intends to comment on the general state of a contest. Worse, many people have (seemingly accidentally) replied to a story-specific comment in the general discussion thread instead of the relevant story, preventing their reply from showing up underneath said story with the proper notifications and such to the author.

I'd propose that the main contest discussion thread be a virtual "story-like" topic of it's own, isolated in the same way as each story is. That said, I think it wouldn't go amiss to have an "all comments" thread/view option as well, which would include all comments, regardless of "topic" and thus basically persist the view the "discussion thread" view currently shows.

**Comment by RogerDodger** [comment]
I'm fairly sure the current behaviour is preferred as default, so I think an upheaval in the sense you describe (in essence, breaking backwards compatibility) would be inappropriate. There's two solutions here I can think of.

In both case, regarding the URL interface:

- /event/<id> shows all posts
- /event/<id>/thread shows only posts not made on a fic/pic

This preserves backwards compatibility so is pretty uncontroversial. Now, the difficult part is deciding how to link to each. Right now there's two links to the discussion thread: the prompt in the header, and the "Discussion thread" button. So the two possible solutions are:

1. Change the "Discussion thread" button to link to /event/<id>/thread
2. Add another button next to "Discussion thread" that links to /event/<id>/thread

The second seems preferable to prevent confusion. However, it's a little inelegant, as I can't think of a particularly good label for it.

**Comment by baxil** [comment]
"All Discussion" / "Non-Story Discussion"?

-Bax

**Comment by RogerDodger** [comment]
Less clear I think. Also imprecise for pic events.
