### ISSUE TITLE
Problems with Writeoff categorization in scoreboard display

### ISSUE THREAD

**Issue by baxil** [RogerDodger/WriteOff#29]
For some reason, when I go to the scoreboard, stories from multiple FIM Writeoffs are visible with the display filtered to "Mode: Fic, Genre: Original".  For example, "Rising From the Ashes" is correctly listed as a FIM Writeoff on the title bar of its pages e.g. https://writeoff.me/event/66-Rising-From-the-Ashes/fic/results , but if you click on the + next to my name in the scoreboard rankings, you can see that round's story counting toward the Original Fiction scoreboard.

It looks like the problem is that "Genre: Original", Format: Blank is listing stories of *both* genres which fit within "Format: Short Story".  If I select both Genre and Format, it displays correctly.

![screenshot 2017-07-13 20 14 33](https://user-images.githubusercontent.com/12451964/28196831-faf6644c-6807-11e7-8d94-cc26626fdf13.png)

**Comment by RogerDodger** [comment]
Fixed.
