### ISSUE TITLE
Request: Add comment statistics to Art gallery pages

### ISSUE THREAD

**Issue by baxil** [RogerDodger/WriteOff#35]
During the review/judging period, often Writeoff veterans will encourage participants to add reviews to the pieces with the least feedback.  This is easy for stories, because in the fic gallery page, the number of comments and the number of unique commenters are visible at a glance.  In order to check those statistics for art submissions, however, someone has to click on each piece one by one and scroll down to the comments section.

This could obviously be fixed by using a story-style display instead of a gallery-style display for art, but that seems inelegant.  Instead I'd like to propose adding a simple parenthetical section on a line underneath each piece's title:

> 🖼
> Submission Name
> (👥 2, 💬 6)

This should be a relatively simple addition with high return on effort, as participants can much more easily track where comments are needed.

**Comment by StarFahx** [comment]
Less simple for smaller return, but the possibility to sort art by comments and participants would be even more helpful for people looking to spread review-love. It's a feature I have used on fics far too much in the past, and I think it'd be really handy alongside statistics for pics.
~Quill (who cba to make a new github account to look sufficiently poni)

**Comment by GroaningGreyAgony** [comment]
Please allow me to third these suggestions.

**Comment by RogerDodger** [comment]
Done. Sorting will be done alongside #38.
