### ISSUE TITLE
Image/youtube tags for BBcode

### ISSUE THREAD

**Issue by ReallyNotAHat** [RogerDodger/WriteOff#4]
Either/or might be useful.

**Comment by RogerDodger** [comment]
I don't really like YouTube embeds. They're noisy, take up a lot of screen space, and are a pretty lazy way to contribute to a conversation. You can link a YouTube video with an ordinary [url] just fine.

Image tags can work if I hide them behind a clickable expand button. The only trouble then is that people will try and link to HTTP images, and the site is HTTPS. Most browsers will not load HTTP resources on a HTTPS page.

To address this I'd have to download and rehost them myself (which would also solve the link rot problem most image hosting sites have). I'm not entirely sure that's a good idea though.

I think a temporary solution of only allowing [img] tags with HTTPS urls in them is okay, though.

**Comment by Otterverse** [comment]
Yeah, the "mixed content" warning stuff made this a lot more complicated in recent years, but having at least some image posting capability would be good. The modern "social network" paradigm starts to fall apart if people can't post their reaction gifs and the like.

That said... please sanitize formatting for max image size (both pixel dimensions and download size) to make that work. We don't need a 50000x50000px  images just repeating "Ot Ot Ot Ot" breaking every page view, or 50GB images being auto-loaded.

**Comment by RogerDodger** [comment]
Resolving this to wontfix. It's more and more clear to me as time passes by that image embeds actively encourage low-effort posts.
